#!/bin/sh
BUILD_DIR=Frank/frankified_build
APP_DIR=$BUILD_DIR/Frankified.app

rm -rf $BUILD_DIR
xcodebuild -xcconfig Frank/frankify.xcconfig install -configuration Debug -sdk iphonesimulator

mv `echo $BUILD_DIR/Applications/*.app` $APP_DIR

cp -r Frank/frank_static_resources.bundle $APP_DIR/frank_static_resources.bundle
