require 'bundler'
require 'rake/testtask'
Bundler::GemHelper.install_tasks

desc 'open up version.rb'
task :edit_version do
  exec "vim #{File.dirname(__FILE__)}/lib/frank-cucumber/version.rb"
end

task :ev => :edit_version

Rake::TestTask.new do |t|
  t.libs << "test"
  t.test_files = FileList['test/*_test.rb','test/*_acceptance.rb']
  t.verbose = true
end

task :default => ["test"]
