//
//  UIQuery+ShelleyCompatibiilityOverrides.m
//  Frank
//
//  Created by Pete Hodgson on 11/4/11.
//  Copyright (c) 2011 ThoughtWorks. All rights reserved.
//

#import "UIQuery.h"
#import "LoadableCategory.h"

MAKE_CATEGORIES_LOADABLE(UIQuery_ShelleyCompatibiilityOverrides)

// Shelley adds predicate methods similar to those below into UIView. Doing that breaks UIQuery's 
// magical autogenerated predicate methods (implemented in UIFilter), so we need to manually add them
// to UIQuery here.
@implementation UIQuery (ShelleyCompatibiilityOverrides)

-(UIQuery *)placeholder:(NSString *)expectedMark {
	return [self.with placeholder:expectedMark];
}

- (UIQuery *) text:(NSString *)expectedText{
	return [self.with text:expectedText];
}

@end
